/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SpacesRouteImport } from './routes/spaces'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as PopupRouteImport } from './routes/popup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SpacesIndexRouteImport } from './routes/spaces.index'
import { Route as SpacesSpaceIdRouteImport } from './routes/spaces.$spaceId'
import { Route as SpacesSpaceIdIndexRouteImport } from './routes/spaces.$spaceId.index'
import { Route as SpacesSpaceIdPomodoroRouteImport } from './routes/spaces.$spaceId.pomodoro'
import { Route as SpacesSpaceIdCalendarRouteImport } from './routes/spaces.$spaceId.calendar'
import { Route as SpacesSpaceIdWithSidebarRouteImport } from './routes/spaces.$spaceId._withSidebar'
import { Route as SpacesSpaceIdTimelineIndexRouteImport } from './routes/spaces.$spaceId.timeline.index'
import { Route as SpacesSpaceIdProjectsIndexRouteImport } from './routes/spaces.$spaceId.projects.index'
import { Route as SpacesSpaceIdDatesIndexRouteImport } from './routes/spaces.$spaceId.dates.index'
import { Route as SpacesSpaceIdDailyReportsIndexRouteImport } from './routes/spaces.$spaceId.daily-reports.index'
import { Route as SpacesSpaceIdTimelineDateRouteImport } from './routes/spaces.$spaceId.timeline.$date'
import { Route as SpacesSpaceIdItemDetailsItemIdRouteImport } from './routes/spaces.$spaceId.item-details.$itemId'
import { Route as SpacesSpaceIdDailyReportsDateRouteImport } from './routes/spaces.$spaceId.daily-reports.$date'
import { Route as SpacesSpaceIdWithSidebarProjectsProjectIdRouteImport } from './routes/spaces.$spaceId._withSidebar.projects.$projectId'
import { Route as SpacesSpaceIdWithSidebarDatesDateRouteImport } from './routes/spaces.$spaceId._withSidebar.dates.$date'

const SpacesRoute = SpacesRouteImport.update({
  id: '/spaces',
  path: '/spaces',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const PopupRoute = PopupRouteImport.update({
  id: '/popup',
  path: '/popup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SpacesIndexRoute = SpacesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SpacesRoute,
} as any)
const SpacesSpaceIdRoute = SpacesSpaceIdRouteImport.update({
  id: '/$spaceId',
  path: '/$spaceId',
  getParentRoute: () => SpacesRoute,
} as any)
const SpacesSpaceIdIndexRoute = SpacesSpaceIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SpacesSpaceIdRoute,
} as any)
const SpacesSpaceIdPomodoroRoute = SpacesSpaceIdPomodoroRouteImport.update({
  id: '/pomodoro',
  path: '/pomodoro',
  getParentRoute: () => SpacesSpaceIdRoute,
} as any)
const SpacesSpaceIdCalendarRoute = SpacesSpaceIdCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => SpacesSpaceIdRoute,
} as any)
const SpacesSpaceIdWithSidebarRoute =
  SpacesSpaceIdWithSidebarRouteImport.update({
    id: '/_withSidebar',
    getParentRoute: () => SpacesSpaceIdRoute,
  } as any)
const SpacesSpaceIdTimelineIndexRoute =
  SpacesSpaceIdTimelineIndexRouteImport.update({
    id: '/timeline/',
    path: '/timeline/',
    getParentRoute: () => SpacesSpaceIdRoute,
  } as any)
const SpacesSpaceIdProjectsIndexRoute =
  SpacesSpaceIdProjectsIndexRouteImport.update({
    id: '/projects/',
    path: '/projects/',
    getParentRoute: () => SpacesSpaceIdRoute,
  } as any)
const SpacesSpaceIdDatesIndexRoute = SpacesSpaceIdDatesIndexRouteImport.update({
  id: '/dates/',
  path: '/dates/',
  getParentRoute: () => SpacesSpaceIdRoute,
} as any)
const SpacesSpaceIdDailyReportsIndexRoute =
  SpacesSpaceIdDailyReportsIndexRouteImport.update({
    id: '/daily-reports/',
    path: '/daily-reports/',
    getParentRoute: () => SpacesSpaceIdRoute,
  } as any)
const SpacesSpaceIdTimelineDateRoute =
  SpacesSpaceIdTimelineDateRouteImport.update({
    id: '/timeline/$date',
    path: '/timeline/$date',
    getParentRoute: () => SpacesSpaceIdRoute,
  } as any)
const SpacesSpaceIdItemDetailsItemIdRoute =
  SpacesSpaceIdItemDetailsItemIdRouteImport.update({
    id: '/item-details/$itemId',
    path: '/item-details/$itemId',
    getParentRoute: () => SpacesSpaceIdRoute,
  } as any)
const SpacesSpaceIdDailyReportsDateRoute =
  SpacesSpaceIdDailyReportsDateRouteImport.update({
    id: '/daily-reports/$date',
    path: '/daily-reports/$date',
    getParentRoute: () => SpacesSpaceIdRoute,
  } as any)
const SpacesSpaceIdWithSidebarProjectsProjectIdRoute =
  SpacesSpaceIdWithSidebarProjectsProjectIdRouteImport.update({
    id: '/projects/$projectId',
    path: '/projects/$projectId',
    getParentRoute: () => SpacesSpaceIdWithSidebarRoute,
  } as any)
const SpacesSpaceIdWithSidebarDatesDateRoute =
  SpacesSpaceIdWithSidebarDatesDateRouteImport.update({
    id: '/dates/$date',
    path: '/dates/$date',
    getParentRoute: () => SpacesSpaceIdWithSidebarRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/popup': typeof PopupRoute
  '/signup': typeof SignupRoute
  '/spaces': typeof SpacesRouteWithChildren
  '/spaces/$spaceId': typeof SpacesSpaceIdRouteWithChildren
  '/spaces/': typeof SpacesIndexRoute
  '/spaces/$spaceId/calendar': typeof SpacesSpaceIdCalendarRoute
  '/spaces/$spaceId/pomodoro': typeof SpacesSpaceIdPomodoroRoute
  '/spaces/$spaceId/': typeof SpacesSpaceIdIndexRoute
  '/spaces/$spaceId/daily-reports/$date': typeof SpacesSpaceIdDailyReportsDateRoute
  '/spaces/$spaceId/item-details/$itemId': typeof SpacesSpaceIdItemDetailsItemIdRoute
  '/spaces/$spaceId/timeline/$date': typeof SpacesSpaceIdTimelineDateRoute
  '/spaces/$spaceId/daily-reports/': typeof SpacesSpaceIdDailyReportsIndexRoute
  '/spaces/$spaceId/dates/': typeof SpacesSpaceIdDatesIndexRoute
  '/spaces/$spaceId/projects/': typeof SpacesSpaceIdProjectsIndexRoute
  '/spaces/$spaceId/timeline/': typeof SpacesSpaceIdTimelineIndexRoute
  '/spaces/$spaceId/dates/$date': typeof SpacesSpaceIdWithSidebarDatesDateRoute
  '/spaces/$spaceId/projects/$projectId': typeof SpacesSpaceIdWithSidebarProjectsProjectIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/popup': typeof PopupRoute
  '/signup': typeof SignupRoute
  '/spaces': typeof SpacesIndexRoute
  '/spaces/$spaceId': typeof SpacesSpaceIdIndexRoute
  '/spaces/$spaceId/calendar': typeof SpacesSpaceIdCalendarRoute
  '/spaces/$spaceId/pomodoro': typeof SpacesSpaceIdPomodoroRoute
  '/spaces/$spaceId/daily-reports/$date': typeof SpacesSpaceIdDailyReportsDateRoute
  '/spaces/$spaceId/item-details/$itemId': typeof SpacesSpaceIdItemDetailsItemIdRoute
  '/spaces/$spaceId/timeline/$date': typeof SpacesSpaceIdTimelineDateRoute
  '/spaces/$spaceId/daily-reports': typeof SpacesSpaceIdDailyReportsIndexRoute
  '/spaces/$spaceId/dates': typeof SpacesSpaceIdDatesIndexRoute
  '/spaces/$spaceId/projects': typeof SpacesSpaceIdProjectsIndexRoute
  '/spaces/$spaceId/timeline': typeof SpacesSpaceIdTimelineIndexRoute
  '/spaces/$spaceId/dates/$date': typeof SpacesSpaceIdWithSidebarDatesDateRoute
  '/spaces/$spaceId/projects/$projectId': typeof SpacesSpaceIdWithSidebarProjectsProjectIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/popup': typeof PopupRoute
  '/signup': typeof SignupRoute
  '/spaces': typeof SpacesRouteWithChildren
  '/spaces/$spaceId': typeof SpacesSpaceIdRouteWithChildren
  '/spaces/': typeof SpacesIndexRoute
  '/spaces/$spaceId/_withSidebar': typeof SpacesSpaceIdWithSidebarRouteWithChildren
  '/spaces/$spaceId/calendar': typeof SpacesSpaceIdCalendarRoute
  '/spaces/$spaceId/pomodoro': typeof SpacesSpaceIdPomodoroRoute
  '/spaces/$spaceId/': typeof SpacesSpaceIdIndexRoute
  '/spaces/$spaceId/daily-reports/$date': typeof SpacesSpaceIdDailyReportsDateRoute
  '/spaces/$spaceId/item-details/$itemId': typeof SpacesSpaceIdItemDetailsItemIdRoute
  '/spaces/$spaceId/timeline/$date': typeof SpacesSpaceIdTimelineDateRoute
  '/spaces/$spaceId/daily-reports/': typeof SpacesSpaceIdDailyReportsIndexRoute
  '/spaces/$spaceId/dates/': typeof SpacesSpaceIdDatesIndexRoute
  '/spaces/$spaceId/projects/': typeof SpacesSpaceIdProjectsIndexRoute
  '/spaces/$spaceId/timeline/': typeof SpacesSpaceIdTimelineIndexRoute
  '/spaces/$spaceId/_withSidebar/dates/$date': typeof SpacesSpaceIdWithSidebarDatesDateRoute
  '/spaces/$spaceId/_withSidebar/projects/$projectId': typeof SpacesSpaceIdWithSidebarProjectsProjectIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/popup'
    | '/signup'
    | '/spaces'
    | '/spaces/$spaceId'
    | '/spaces/'
    | '/spaces/$spaceId/calendar'
    | '/spaces/$spaceId/pomodoro'
    | '/spaces/$spaceId/'
    | '/spaces/$spaceId/daily-reports/$date'
    | '/spaces/$spaceId/item-details/$itemId'
    | '/spaces/$spaceId/timeline/$date'
    | '/spaces/$spaceId/daily-reports/'
    | '/spaces/$spaceId/dates/'
    | '/spaces/$spaceId/projects/'
    | '/spaces/$spaceId/timeline/'
    | '/spaces/$spaceId/dates/$date'
    | '/spaces/$spaceId/projects/$projectId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/popup'
    | '/signup'
    | '/spaces'
    | '/spaces/$spaceId'
    | '/spaces/$spaceId/calendar'
    | '/spaces/$spaceId/pomodoro'
    | '/spaces/$spaceId/daily-reports/$date'
    | '/spaces/$spaceId/item-details/$itemId'
    | '/spaces/$spaceId/timeline/$date'
    | '/spaces/$spaceId/daily-reports'
    | '/spaces/$spaceId/dates'
    | '/spaces/$spaceId/projects'
    | '/spaces/$spaceId/timeline'
    | '/spaces/$spaceId/dates/$date'
    | '/spaces/$spaceId/projects/$projectId'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/popup'
    | '/signup'
    | '/spaces'
    | '/spaces/$spaceId'
    | '/spaces/'
    | '/spaces/$spaceId/_withSidebar'
    | '/spaces/$spaceId/calendar'
    | '/spaces/$spaceId/pomodoro'
    | '/spaces/$spaceId/'
    | '/spaces/$spaceId/daily-reports/$date'
    | '/spaces/$spaceId/item-details/$itemId'
    | '/spaces/$spaceId/timeline/$date'
    | '/spaces/$spaceId/daily-reports/'
    | '/spaces/$spaceId/dates/'
    | '/spaces/$spaceId/projects/'
    | '/spaces/$spaceId/timeline/'
    | '/spaces/$spaceId/_withSidebar/dates/$date'
    | '/spaces/$spaceId/_withSidebar/projects/$projectId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  PopupRoute: typeof PopupRoute
  SignupRoute: typeof SignupRoute
  SpacesRoute: typeof SpacesRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/spaces': {
      id: '/spaces'
      path: '/spaces'
      fullPath: '/spaces'
      preLoaderRoute: typeof SpacesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/popup': {
      id: '/popup'
      path: '/popup'
      fullPath: '/popup'
      preLoaderRoute: typeof PopupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spaces/': {
      id: '/spaces/'
      path: '/'
      fullPath: '/spaces/'
      preLoaderRoute: typeof SpacesIndexRouteImport
      parentRoute: typeof SpacesRoute
    }
    '/spaces/$spaceId': {
      id: '/spaces/$spaceId'
      path: '/$spaceId'
      fullPath: '/spaces/$spaceId'
      preLoaderRoute: typeof SpacesSpaceIdRouteImport
      parentRoute: typeof SpacesRoute
    }
    '/spaces/$spaceId/': {
      id: '/spaces/$spaceId/'
      path: '/'
      fullPath: '/spaces/$spaceId/'
      preLoaderRoute: typeof SpacesSpaceIdIndexRouteImport
      parentRoute: typeof SpacesSpaceIdRoute
    }
    '/spaces/$spaceId/pomodoro': {
      id: '/spaces/$spaceId/pomodoro'
      path: '/pomodoro'
      fullPath: '/spaces/$spaceId/pomodoro'
      preLoaderRoute: typeof SpacesSpaceIdPomodoroRouteImport
      parentRoute: typeof SpacesSpaceIdRoute
    }
    '/spaces/$spaceId/calendar': {
      id: '/spaces/$spaceId/calendar'
      path: '/calendar'
      fullPath: '/spaces/$spaceId/calendar'
      preLoaderRoute: typeof SpacesSpaceIdCalendarRouteImport
      parentRoute: typeof SpacesSpaceIdRoute
    }
    '/spaces/$spaceId/_withSidebar': {
      id: '/spaces/$spaceId/_withSidebar'
      path: ''
      fullPath: '/spaces/$spaceId'
      preLoaderRoute: typeof SpacesSpaceIdWithSidebarRouteImport
      parentRoute: typeof SpacesSpaceIdRoute
    }
    '/spaces/$spaceId/timeline/': {
      id: '/spaces/$spaceId/timeline/'
      path: '/timeline'
      fullPath: '/spaces/$spaceId/timeline/'
      preLoaderRoute: typeof SpacesSpaceIdTimelineIndexRouteImport
      parentRoute: typeof SpacesSpaceIdRoute
    }
    '/spaces/$spaceId/projects/': {
      id: '/spaces/$spaceId/projects/'
      path: '/projects'
      fullPath: '/spaces/$spaceId/projects/'
      preLoaderRoute: typeof SpacesSpaceIdProjectsIndexRouteImport
      parentRoute: typeof SpacesSpaceIdRoute
    }
    '/spaces/$spaceId/dates/': {
      id: '/spaces/$spaceId/dates/'
      path: '/dates'
      fullPath: '/spaces/$spaceId/dates/'
      preLoaderRoute: typeof SpacesSpaceIdDatesIndexRouteImport
      parentRoute: typeof SpacesSpaceIdRoute
    }
    '/spaces/$spaceId/daily-reports/': {
      id: '/spaces/$spaceId/daily-reports/'
      path: '/daily-reports'
      fullPath: '/spaces/$spaceId/daily-reports/'
      preLoaderRoute: typeof SpacesSpaceIdDailyReportsIndexRouteImport
      parentRoute: typeof SpacesSpaceIdRoute
    }
    '/spaces/$spaceId/timeline/$date': {
      id: '/spaces/$spaceId/timeline/$date'
      path: '/timeline/$date'
      fullPath: '/spaces/$spaceId/timeline/$date'
      preLoaderRoute: typeof SpacesSpaceIdTimelineDateRouteImport
      parentRoute: typeof SpacesSpaceIdRoute
    }
    '/spaces/$spaceId/item-details/$itemId': {
      id: '/spaces/$spaceId/item-details/$itemId'
      path: '/item-details/$itemId'
      fullPath: '/spaces/$spaceId/item-details/$itemId'
      preLoaderRoute: typeof SpacesSpaceIdItemDetailsItemIdRouteImport
      parentRoute: typeof SpacesSpaceIdRoute
    }
    '/spaces/$spaceId/daily-reports/$date': {
      id: '/spaces/$spaceId/daily-reports/$date'
      path: '/daily-reports/$date'
      fullPath: '/spaces/$spaceId/daily-reports/$date'
      preLoaderRoute: typeof SpacesSpaceIdDailyReportsDateRouteImport
      parentRoute: typeof SpacesSpaceIdRoute
    }
    '/spaces/$spaceId/_withSidebar/projects/$projectId': {
      id: '/spaces/$spaceId/_withSidebar/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/spaces/$spaceId/projects/$projectId'
      preLoaderRoute: typeof SpacesSpaceIdWithSidebarProjectsProjectIdRouteImport
      parentRoute: typeof SpacesSpaceIdWithSidebarRoute
    }
    '/spaces/$spaceId/_withSidebar/dates/$date': {
      id: '/spaces/$spaceId/_withSidebar/dates/$date'
      path: '/dates/$date'
      fullPath: '/spaces/$spaceId/dates/$date'
      preLoaderRoute: typeof SpacesSpaceIdWithSidebarDatesDateRouteImport
      parentRoute: typeof SpacesSpaceIdWithSidebarRoute
    }
  }
}

interface SpacesSpaceIdWithSidebarRouteChildren {
  SpacesSpaceIdWithSidebarDatesDateRoute: typeof SpacesSpaceIdWithSidebarDatesDateRoute
  SpacesSpaceIdWithSidebarProjectsProjectIdRoute: typeof SpacesSpaceIdWithSidebarProjectsProjectIdRoute
}

const SpacesSpaceIdWithSidebarRouteChildren: SpacesSpaceIdWithSidebarRouteChildren =
  {
    SpacesSpaceIdWithSidebarDatesDateRoute:
      SpacesSpaceIdWithSidebarDatesDateRoute,
    SpacesSpaceIdWithSidebarProjectsProjectIdRoute:
      SpacesSpaceIdWithSidebarProjectsProjectIdRoute,
  }

const SpacesSpaceIdWithSidebarRouteWithChildren =
  SpacesSpaceIdWithSidebarRoute._addFileChildren(
    SpacesSpaceIdWithSidebarRouteChildren,
  )

interface SpacesSpaceIdRouteChildren {
  SpacesSpaceIdWithSidebarRoute: typeof SpacesSpaceIdWithSidebarRouteWithChildren
  SpacesSpaceIdCalendarRoute: typeof SpacesSpaceIdCalendarRoute
  SpacesSpaceIdPomodoroRoute: typeof SpacesSpaceIdPomodoroRoute
  SpacesSpaceIdIndexRoute: typeof SpacesSpaceIdIndexRoute
  SpacesSpaceIdDailyReportsDateRoute: typeof SpacesSpaceIdDailyReportsDateRoute
  SpacesSpaceIdItemDetailsItemIdRoute: typeof SpacesSpaceIdItemDetailsItemIdRoute
  SpacesSpaceIdTimelineDateRoute: typeof SpacesSpaceIdTimelineDateRoute
  SpacesSpaceIdDailyReportsIndexRoute: typeof SpacesSpaceIdDailyReportsIndexRoute
  SpacesSpaceIdDatesIndexRoute: typeof SpacesSpaceIdDatesIndexRoute
  SpacesSpaceIdProjectsIndexRoute: typeof SpacesSpaceIdProjectsIndexRoute
  SpacesSpaceIdTimelineIndexRoute: typeof SpacesSpaceIdTimelineIndexRoute
}

const SpacesSpaceIdRouteChildren: SpacesSpaceIdRouteChildren = {
  SpacesSpaceIdWithSidebarRoute: SpacesSpaceIdWithSidebarRouteWithChildren,
  SpacesSpaceIdCalendarRoute: SpacesSpaceIdCalendarRoute,
  SpacesSpaceIdPomodoroRoute: SpacesSpaceIdPomodoroRoute,
  SpacesSpaceIdIndexRoute: SpacesSpaceIdIndexRoute,
  SpacesSpaceIdDailyReportsDateRoute: SpacesSpaceIdDailyReportsDateRoute,
  SpacesSpaceIdItemDetailsItemIdRoute: SpacesSpaceIdItemDetailsItemIdRoute,
  SpacesSpaceIdTimelineDateRoute: SpacesSpaceIdTimelineDateRoute,
  SpacesSpaceIdDailyReportsIndexRoute: SpacesSpaceIdDailyReportsIndexRoute,
  SpacesSpaceIdDatesIndexRoute: SpacesSpaceIdDatesIndexRoute,
  SpacesSpaceIdProjectsIndexRoute: SpacesSpaceIdProjectsIndexRoute,
  SpacesSpaceIdTimelineIndexRoute: SpacesSpaceIdTimelineIndexRoute,
}

const SpacesSpaceIdRouteWithChildren = SpacesSpaceIdRoute._addFileChildren(
  SpacesSpaceIdRouteChildren,
)

interface SpacesRouteChildren {
  SpacesSpaceIdRoute: typeof SpacesSpaceIdRouteWithChildren
  SpacesIndexRoute: typeof SpacesIndexRoute
}

const SpacesRouteChildren: SpacesRouteChildren = {
  SpacesSpaceIdRoute: SpacesSpaceIdRouteWithChildren,
  SpacesIndexRoute: SpacesIndexRoute,
}

const SpacesRouteWithChildren =
  SpacesRoute._addFileChildren(SpacesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  PopupRoute: PopupRoute,
  SignupRoute: SignupRoute,
  SpacesRoute: SpacesRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
