/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as Timeline2IndexRouteImport } from './routes/timeline2/index'
import { Route as Timeline2DateRouteImport } from './routes/timeline2/$date'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const Timeline2IndexRoute = Timeline2IndexRouteImport.update({
  id: '/timeline2/',
  path: '/timeline2/',
  getParentRoute: () => rootRouteImport,
} as any)
const Timeline2DateRoute = Timeline2DateRouteImport.update({
  id: '/timeline2/$date',
  path: '/timeline2/$date',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/timeline2/$date': typeof Timeline2DateRoute
  '/timeline2': typeof Timeline2IndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/timeline2/$date': typeof Timeline2DateRoute
  '/timeline2': typeof Timeline2IndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/timeline2/$date': typeof Timeline2DateRoute
  '/timeline2/': typeof Timeline2IndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/timeline2/$date' | '/timeline2'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/timeline2/$date' | '/timeline2'
  id: '__root__' | '/' | '/timeline2/$date' | '/timeline2/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  Timeline2DateRoute: typeof Timeline2DateRoute
  Timeline2IndexRoute: typeof Timeline2IndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/timeline2/': {
      id: '/timeline2/'
      path: '/timeline2'
      fullPath: '/timeline2'
      preLoaderRoute: typeof Timeline2IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/timeline2/$date': {
      id: '/timeline2/$date'
      path: '/timeline2/$date'
      fullPath: '/timeline2/$date'
      preLoaderRoute: typeof Timeline2DateRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  Timeline2DateRoute: Timeline2DateRoute,
  Timeline2IndexRoute: Timeline2IndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
