import { defineCollection, z } from "astro:content";
import { glob } from "astro/loaders";

// Files here are generated by `pnpm sync:releases` from the GitHub releases and
// then hand-polished. The frontmatter is what the overview page, the meta tags
// and the structured data are built from, so it is kept separate from the body.
const releases = defineCollection({
  loader: glob({ base: "./src/content/releases", pattern: "**/*.md" }),
  schema: z.object({
    /** Git tag, also the URL slug: /releases/v0.10.1/ */
    tag: z.string(),
    /** Tag without the leading "v", used for schema.org softwareVersion. */
    version: z.string(),
    /** Short headline shown next to the version. */
    headline: z.string(),
    /** Meta description and the blurb on the overview page. Keep under ~160 chars. */
    summary: z.string(),
    highlights: z.array(z.string()).default([]),
    publishedAt: z.coerce.date(),
    githubUrl: z.string().url(),
    compareUrl: z.string().url().optional(),
    prerelease: z.boolean().default(false),
  }),
});

export const collections = { releases };
