import { defineCollection, z } from "astro:content";
import { glob } from "astro/loaders";
import { docsLoader } from "@astrojs/starlight/loaders";
import { docsSchema } from "@astrojs/starlight/schema";
import { RELEASE_TAG_MESSAGE, RELEASE_TAG_PATTERN } from "./lib/releaseTag";

// Files here are generated by `pnpm sync:releases` from the GitHub releases and
// then hand-polished. The frontmatter is what the overview page, the meta tags
// and the structured data are built from, so it is kept separate from the body.
const releases = defineCollection({
  loader: glob({ base: "./src/content/releases", pattern: "**/*.md" }),
  schema: z.object({
    /** Git tag, also the file name and the URL slug: /releases/v0.10.1/ */
    tag: z.string().regex(RELEASE_TAG_PATTERN, RELEASE_TAG_MESSAGE),
    /** Tag without the leading "v", used for schema.org softwareVersion. */
    version: z.string(),
    /** Short headline shown next to the version. */
    headline: z.string(),
    /** Meta description and the blurb on the overview page. Keep under ~160 chars. */
    summary: z.string(),
    highlights: z.array(z.string()).default([]),
    publishedAt: z.coerce.date(),
    githubUrl: z.string().url(),
    compareUrl: z.string().url().optional(),
    prerelease: z.boolean().default(false),
  }),
});

// Starlight owns this collection. Pages live one level deeper, in
// `src/content/docs/docs/`, which is how Starlight serves them from /docs/ and
// leaves the landing routes in `src/pages/` alone.
const docs = defineCollection({
  loader: docsLoader(),
  schema: docsSchema(),
});

export const collections = { releases, docs };
